version: "3.3"

services:

  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-data/certs:/etc/nginx/certs
    networks:
      - nginx-proxy

  app1:
    container_name: app1
    build: 
      context: ./php-apache
    volumes:
      - ../projeto1:/var/www/html
    env_file: 
      - ./environment/app1.env
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    driver: bridge